### PR TITLE
Improving CMakeLists.txt in ARX/ARUtil for the build process.

### PR DESCRIPTION
**Pull request by kalwalt**
Related to this issue https://github.com/augmentmy-world/artoolkitX.js/issues/1 and the PR https://github.com/augmentmy-world/artoolkitX.js/pull/2 In my sytem i had to make this modification and  i need to add the files stb_image.h stb_image_write.h in the /depends/emscripten/include/stb_image folder. Without those files and includes cmake fails, and consequently the build process stop.
This needs to verified in another OS and machine.

### CODE REVIEW

**Comment by ThorstenBux** [comment]
@kalwalt what system are you on? I'm on macOS

**Comment by kalwalt** [comment]
I am on a linux machine with installed Ubuntu 18.04. Did you build without the stb_image? Maybe an issue with emscripten?

**Comment by ThorstenBux** [comment]
I could build without stb_image on macOS 10.14.5  using Emscripten 
```
Zaphod:~ thorstenbux$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.40
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 1b4148f39a69c7fc62edadd85e4122b68694dfb7) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Users/thorstenbux/repos/emsdk/fastcomp/fastcomp/bin
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by ThorstenBux** [comment]
I'm happy to add it. Just wondering why I don't need it

**Comment by kalwalt** [comment]
Maybe you use a newer Emscripten version thank mine. I Will check when i go back to my PC this afternoon.

**Comment by kalwalt** [comment]
```shell
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.41
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 1b4148f39a69c7fc62edadd85e4122b68694dfb7) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/walter/emsdk/fastcomp/fastcomp/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

```
it seems not so different, but maybe cmake search a stub_image pkg? I will do a little re-search on this.

**Comment by kalwalt** [comment]
I made this test; In artoolkitx after this line https://github.com/augmentmy-world/artoolkitx/blob/4ce65570a4d1541de582abfcbf69f8386f8493dd/Source/CMakeLists.txt#L106 add:

`message( "CMAKE_FIND_ROOT_PATH is ${CMAKE_FIND_ROOT_PATH}" ) `

you should get in the console a list of paths that cmake look at, my list of path is:

```shell
Building emscripten
-- Using single-configuration CMake generator.
JPEG_INCLUDE_DIR /home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/depends/emscripten/libjpeg/
CMAKE_FIND_ROOT_PATH is /home/walter/emsdk/fastcomp/emscripten/system;/home/walter/emsdk/fastcomp/emscripten/system;/home/walter/emsdk/fastcomp/emscripten/system;/home/walter/emsdk/fastcomp/emscripten/system;/home/walter/emsdk/fastcomp/emscripten/system;/home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/depends/
```
because the stb_image.h stb_write.h files are not in those folders, it fails.

**Comment by ThorstenBux** [comment]
I'm in the process to rebasing this branch to artoolkitX/master. There is only one issue that I need to solve. Then I can look into this.

If you would like to support let me know and I push the merged branch

**Comment by kalwalt** [comment]
yes if you want i can test it. :smile: 
It would be nice also to test in windows OS, Unluckily i have only ubuntu installed on my machine.

**Comment by ThorstenBux** [comment]
I think I've fixed it. I've pushed to emscripten branch. If you find the time please pull and try if you can build it.

**Comment by ThorstenBux** [comment]
We should setup a CI system. I like Bitrise and build it constantly with Emscripten on Docker that shouldn't be too hard.
For windows build I can do in a VM or we can build it on VS TeamServices :)

**Comment by kalwalt** [comment]
I pulled your latest but i still get the stb error, look at the end of the log:

```shell
 ./build.sh emscripten

Building emscripten
-- Using single-configuration CMake generator.
JPEG_INCLUDE_DIR /home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/depends/emscripten/libjpeg/
-- Could NOT find OpenCV (missing: OpenCV_LIBS OpenCV_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:169 (message):
  OpenCV not found, will build without 2D tracker


-- Defined: ARX_TARGET_PLATFORM_EMSCRIPTEN=1
-- Could NOT find OpenGLES2 (missing:  OPENGLES2_LIBRARIES OPENGLES2_INCLUDE_DIR)
/usr/usr/local/opt/local
-- Could NOT find OpenGL3 (missing: OpenGL3_LIBRARIES OpenGL3_INCLUDE_PATH) 
-- Opting for desktop OpenGL. Set ARX_GL_PREFER_EMBEDDED to change.
CMake Warning at ARX/CMakeLists.txt:84 (find_package):
  By not providing "FindGTSAM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GTSAM", but
  CMake did not find one.

  Could not find a package configuration file provided by "GTSAM" with any of
  the following names:

    GTSAMConfig.cmake
    gtsam-config.cmake

  Add the installation prefix of "GTSAM" to CMAKE_PREFIX_PATH or set
  "GTSAM_DIR" to a directory containing one of the above files.  If "GTSAM"
  provides a separate development package or SDK, be sure it has been
  installed.


CMAKE_CURRENT_BINARY_DIR: /home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/build-em/artoolkitx.js
CMAKE_BUILD_TYPE: Release
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/ARX/ARUtil/STB_INCLUDE_DIR
   used as include directory in directory /home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/ARX/ARUtil

-- Configuring incomplete, errors occurred!
See also "/home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/build-em/CMakeFiles/CMakeOutput.log".
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/walter/emsdk/node/8.9.1_64bit/bin/node" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-s USE_LIBJPEG -DCMAKE_C_FLAGS=-s USE_LIBJPEG -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -O3 -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -O3 -DCMAKE_TOOLCHAIN_FILE=/home/walter/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake at /home/walter/kalwalt-github/artoolkitX.js/Source/extras/artoolkitx/Source/build-em

```

> We should setup a CI system. I like Bitrise and build it constantly with Emscripten on Docker that shouldn't be too hard.

i never used it, and what about travis? but honestly i don't have such experience in this field.

> For windows build I can do in a VM or we can build it on VS TeamServices :)

VS TeamServices  i heard of them, but does it is a free service?

**Comment by kalwalt** [comment]
Could be that macOS platform is not affected by this issue because there is a [stb_image folder](https://github.com/augmentmy-world/artoolkitx/tree/emscripten/Source/depends/macos/include/stb_image) ?

**Comment by ThorstenBux** [comment]
I would say just add the additional needed files to the dependency/emscripten directory then it should build and we can continue. I would tell CMake to only read the files when OS is Linux

**Comment by kalwalt** [comment]
Now cmake search stb_image files in the emscripten/depends folder only if the Host machine is Linux, i'm quite sure that is correct. I will re-check and then it will be ready to be merged.

**Comment by kalwalt** [comment]
i tested adding this patch to the master branch, running `./build linux` the compilation was ok, without adding the stb_image files, so this problem appear only with emscripten on a Linux machine.

**Pull request merged**
